"""tenant baseline

Revision ID: t0001
Revises: 
Create Date: 2026-09-23 08:56:28.416973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 't0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_status_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.String(length=64), nullable=True),
    sa.Column('to_status', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_status_log_application_id'), 'application_status_log', ['application_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('matched_job_id', sa.String(length=36), nullable=False),
    sa.Column('portal', sa.String(length=32), nullable=False),
    sa.Column('portal_job_id', sa.String(length=256), nullable=False),
    sa.Column('portal_application_id', sa.String(length=256), nullable=True),
    sa.Column('job_title', sa.String(length=512), nullable=False),
    sa.Column('company', sa.String(length=256), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending_hitl', 'applying', 'applied', 'viewed', 'shortlisted', 'interview_scheduled', 'rejected', 'withdrawn', 'failed_portal_error', 'failed_low_match', 'failed_missing_info', name='app_status_enum'), nullable=False),
    sa.Column('failure_reason', sa.Enum('portal_rejected', 'low_match_score', 'missing_profile_info', 'session_expired', 'unknown', name='app_failure_reason_enum'), nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.Column('tailored_resume_id', sa.String(length=36), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_matched_job_id'), 'applications', ['matched_job_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portal', sa.String(length=32), nullable=False),
    sa.Column('portal_job_id', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('company', sa.String(length=256), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=False),
    sa.Column('job_url', sa.String(length=1024), nullable=False),
    sa.Column('description_snippet', sa.Text(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('explainability', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_portal'), 'jobs', ['portal'], unique=False)
    op.create_table('master_resume',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('minio_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=256), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('missing_info_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portal', sa.String(length=32), nullable=False),
    sa.Column('field_name', sa.String(length=128), nullable=False),
    sa.Column('field_label', sa.String(length=256), nullable=False),
    sa.Column('encountered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('portal', sa.String(length=32), nullable=False),
    sa.Column('job_title', sa.String(length=512), nullable=False),
    sa.Column('match_score_at_apply', sa.Float(), nullable=False),
    sa.Column('outcome', sa.Enum('interview_scheduled', 'offer_received', 'rejected_by_recruiter', 'no_response', 'withdrawn_by_user', name='outcome_signal_enum'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_feedback_application_id'), 'ml_feedback', ['application_id'], unique=False)
    op.create_table('notification_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.Enum('in_app', 'email', 'telegram', 'discord', name='notif_channel_enum'), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('body_snippet', sa.Text(), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('desired_roles', sa.JSON(), nullable=False),
    sa.Column('preferred_locations', sa.JSON(), nullable=False),
    sa.Column('salary_min_lpa', sa.Integer(), nullable=True),
    sa.Column('notice_period_days', sa.Integer(), nullable=False),
    sa.Column('wfh_preference', sa.Enum('onsite', 'hybrid', 'remote', 'any', name='wfh_pref_enum'), nullable=False),
    sa.Column('llm_choice', sa.Enum('self_hosted', 'api', name='llm_choice_enum'), nullable=False),
    sa.Column('notification_platform', sa.Enum('telegram', 'discord', name='notif_platform_enum'), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=True),
    sa.Column('discord_channel_id', sa.String(length=64), nullable=True),
    sa.Column('auto_apply_enabled', sa.Boolean(), nullable=False),
    sa.Column('hitl_enabled', sa.Boolean(), nullable=False),
    sa.Column('match_threshold', sa.Float(), nullable=False),
    sa.Column('apply_cap_daily', sa.Integer(), nullable=False),
    sa.Column('status_check_frequency_hours', sa.Integer(), nullable=False),
    sa.Column('portal_apply_caps', sa.JSON(), nullable=False),
    sa.Column('company_blacklist', sa.JSON(), nullable=False),
    sa.Column('title_blacklist', sa.JSON(), nullable=False),
    sa.Column('auto_apply_paused', sa.Boolean(), nullable=False),
    sa.Column('pause_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('full_name_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('phone_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('current_role', sa.String(length=256), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('work_history', sa.JSON(), nullable=False),
    sa.Column('education', sa.JSON(), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screening_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portal', sa.String(length=32), nullable=False),
    sa.Column('question_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('auto_generated', sa.Boolean(), nullable=False),
    sa.Column('user_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_answers_portal'), 'screening_answers', ['portal'], unique=False)
    op.create_index(op.f('ix_screening_answers_question_fingerprint'), 'screening_answers', ['question_fingerprint'], unique=False)
    op.create_table('skill_match_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tfidf_vector', sa.JSON(), nullable=False),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('skill_name', sa.String(length=256), nullable=False),
    sa.Column('taxonomy_id', sa.String(length=64), nullable=True),
    sa.Column('proficiency', sa.String(length=32), nullable=False),
    sa.Column('years_used', sa.Float(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_skill_name'), 'skills', ['skill_name'], unique=False)
    op.create_table('tailored_resumes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('minio_key', sa.String(length=512), nullable=False),
    sa.Column('llm_choice_used', sa.String(length=32), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purged', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tailored_resumes_job_id'), 'tailored_resumes', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tailored_resumes_job_id'), table_name='tailored_resumes')
    op.drop_table('tailored_resumes')
    op.drop_index(op.f('ix_skills_skill_name'), table_name='skills')
    op.drop_table('skills')
    op.drop_table('skill_match_cache')
    op.drop_index(op.f('ix_screening_answers_question_fingerprint'), table_name='screening_answers')
    op.drop_index(op.f('ix_screening_answers_portal'), table_name='screening_answers')
    op.drop_table('screening_answers')
    op.drop_table('profile')
    op.drop_table('preferences')
    op.drop_table('notification_log')
    op.drop_index(op.f('ix_ml_feedback_application_id'), table_name='ml_feedback')
    op.drop_table('ml_feedback')
    op.drop_table('missing_info_log')
    op.drop_table('master_resume')
    op.drop_index(op.f('ix_jobs_portal'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_applications_matched_job_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_application_status_log_application_id'), table_name='application_status_log')
    op.drop_table('application_status_log')
    # ### end Alembic commands ###
