#!/usr/bin/env node

'use strict';

// Compose a harness PR body from quality-card + walkthrough (+ optional extras).
// Used by /build Phase 11 and wave-pr so humans always get the same surfaces.
//
//   node pr-body.js [--root <dir>] [--title "..."] [--closes N] [--extra path]
//   Prints markdown body to stdout. Exit 1 if quality-card missing or FAIL when
//   --require-gate is set (default for CI/PR open).

const fs = require('fs');
const path = require('path');
const { buildCard, writeCard } = require('./quality-card');
const { buildWalkthrough, writeWalkthrough } = require('./pr-walkthrough');

function readText(file) {
  try {
    return fs.readFileSync(file, 'utf8');
  } catch (_) {
    return null;
  }
}

function arg(argv, name, fb) {
  const i = argv.indexOf(name);
  return i === -1 ? fb : argv[i + 1];
}

function hasFlag(argv, name) {
  return argv.includes(name);
}

function ensureArtifacts(root, base) {
  const cardPath = path.join(root, 'specs', 'reviews', 'quality-card.md');
  const walkPath = path.join(root, 'specs', 'reviews', 'walkthrough.md');
  if (!fs.existsSync(walkPath)) {
    writeWalkthrough(root, buildWalkthrough({ root, base }));
  }
  if (!fs.existsSync(cardPath)) {
    writeCard(root, buildCard({ root }));
  } else {
    // Refresh card so it picks up walkthrough presence
    writeCard(root, buildCard({ root }));
  }
}

function composeBody({
  root = process.cwd(),
  title = null,
  closes = null,
  base = null,
  extraPaths = [],
} = {}) {
  ensureArtifacts(root, base);
  const cardMd = readText(path.join(root, 'specs', 'reviews', 'quality-card.md')) || '';
  const walkMd = readText(path.join(root, 'specs', 'reviews', 'walkthrough.md')) || '';
  const cardJson = (() => {
    try {
      return JSON.parse(fs.readFileSync(path.join(root, 'specs', 'reviews', 'quality-card.json'), 'utf8'));
    } catch (_) {
      return null;
    }
  })();

  const lines = [];
  if (closes) lines.push(`Closes #${closes}`, '');
  if (title) lines.push(`## ${title}`, '');

  lines.push(
    '## Quality card',
    '',
    cardMd.trim() || '_Run `/gate` then `node .claude/scripts/quality-card.js`._',
    '',
    '## Walkthrough',
    '',
    walkMd.trim() || '_Run `node .claude/scripts/pr-walkthrough.js`._',
    '',
  );

  lines.push(
    '## Navigation',
    '',
    '- Human homepage: `docs/CODEBASE.md`',
    '- DeepWiki: `specs/brownfield/wiki/WIKI.md`',
    '- Ask the codebase: `npm run ask -- "your question"`',
    '',
  );

  for (const rel of extraPaths) {
    const text = readText(path.join(root, rel));
    if (text) {
      lines.push(`## ${path.basename(rel)}`, '', text.trim(), '');
    }
  }

  lines.push(
    '---',
    '',
    '_Generated by Claude Harness (`pr-body.js`). Merge stays human-owned._',
    '',
  );

  return {
    body: lines.join('\n'),
    pass: cardJson ? Boolean(cardJson.pass) : false,
    card: cardJson,
  };
}

function main(argv = process.argv.slice(2)) {
  const root = arg(argv, '--root', process.cwd());
  const title = arg(argv, '--title', null);
  const closes = arg(argv, '--closes', null);
  const base = arg(argv, '--base', null);
  const requireGate = hasFlag(argv, '--require-gate') || !hasFlag(argv, '--no-require-gate');
  // Default: require gate (pass) unless --no-require-gate
  const extras = [];
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--extra' && argv[i + 1]) extras.push(argv[++i]);
  }

  const { body, pass } = composeBody({
    root,
    title,
    closes,
    base,
    extraPaths: extras,
  });
  process.stdout.write(body);

  if (requireGate && !hasFlag(argv, '--no-require-gate') && !pass) {
    process.stderr.write(
      'pr-body: quality-card is FAIL or incomplete — refuse PR open without a green /gate receipt '
      + '(use --no-require-gate only for drafts).\n',
    );
    return 1;
  }
  return 0;
}

if (require.main === module) {
  try {
    process.exit(main());
  } catch (e) {
    process.stderr.write(`pr-body: ${e.message}\n`);
    process.exit(2);
  }
}

module.exports = { composeBody, ensureArtifacts, main };
