"""Generate and write .env file from wizard configuration."""
import os
import secrets
import string


def _fernet_key() -> str:
    """Generate a Fernet key without requiring cryptography package at installer time."""
    try:
        from cryptography.fernet import Fernet
        return Fernet.generate_key().decode()
    except ImportError:
        # Fernet key is 32 bytes, URL-safe base64-encoded — approximate with secrets
        import base64
        raw = secrets.token_bytes(32)
        return base64.urlsafe_b64encode(raw).decode()


def _db_url(config: dict) -> str:
    mode = config.get("db_mode", "bundled")
    host = config.get("db_host", "db")
    port = config.get("db_port", "5432")
    name = config.get("db_name", "jhans")
    user = config.get("db_user", "jhans")
    pwd = config.get("db_password", "")
    if mode == "bundled":
        host = "db"
    return f"postgresql://{user}:{pwd}@{host}:{port}/{name}"


def write_env(config: dict, install_dir: str) -> str:
    """
    Generate .env content from wizard config and write to install_dir/.env.
    Returns the path to the written file.
    """
    os.makedirs(install_dir, exist_ok=True)

    secret_key = secrets.token_urlsafe(32)
    fernet_key = _fernet_key()

    db_password = config.get("db_password", "") or secrets.token_urlsafe(16)
    minio_secret = secrets.token_urlsafe(16)

    llm_choice = config.get("llm_choice", "ollama")
    ollama_model = config.get("ollama_model", "llama3")
    anthropic_key = config.get("anthropic_api_key", "")

    email_provider = config.get("email_provider", "smtp")

    lines = [
        "# Generated by jH_ANS Setup Wizard",
        "# Do not edit manually unless you know what you are doing.",
        "",
        "# ── Application ─────────────────────────────────────────────────────────────",
        "APP_ENV=production",
        f"APP_SECRET_KEY={secret_key}",
        f"APP_BASE_URL=http://localhost:8000",
        f"FRONTEND_URL=http://localhost:5173",
        "",
        "# ── Database ─────────────────────────────────────────────────────────────────",
        f"POSTGRES_HOST={config.get('db_host', 'db')}",
        f"POSTGRES_PORT={config.get('db_port', '5432')}",
        f"POSTGRES_DB={config.get('db_name', 'jhans')}",
        f"POSTGRES_USER={config.get('db_user', 'jhans')}",
        f"POSTGRES_PASSWORD={db_password}",
        f"DATABASE_URL={_db_url(config)}",
        "",
        "# ── Redis ────────────────────────────────────────────────────────────────────",
        "REDIS_URL=redis://redis:6379/0",
        "CELERY_BROKER_URL=redis://redis:6379/1",
        "CELERY_RESULT_BACKEND=redis://redis:6379/2",
        "",
        "# ── MinIO ────────────────────────────────────────────────────────────────────",
        "MINIO_ENDPOINT=minio:9000",
        "MINIO_ACCESS_KEY=minioadmin",
        f"MINIO_SECRET_KEY={minio_secret}",
        "MINIO_BUCKET_RESUMES=jhans-resumes",
        "MINIO_SECURE=false",
        "",
        "# ── Encryption ───────────────────────────────────────────────────────────────",
        f"FERNET_KEY={fernet_key}",
        "",
        "# ── OAuth Providers ──────────────────────────────────────────────────────────",
        f"GOOGLE_CLIENT_ID={config.get('google_client_id', '')}",
        f"GOOGLE_CLIENT_SECRET={config.get('google_client_secret', '')}",
        "",
        f"LINKEDIN_CLIENT_ID={config.get('linkedin_client_id', '')}",
        f"LINKEDIN_CLIENT_SECRET={config.get('linkedin_client_secret', '')}",
        "",
        f"FACEBOOK_CLIENT_ID={config.get('facebook_client_id', '')}",
        f"FACEBOOK_CLIENT_SECRET={config.get('facebook_client_secret', '')}",
        "",
        "# ── LLM ──────────────────────────────────────────────────────────────────────",
        f"ANTHROPIC_API_KEY={anthropic_key}",
        f"OLLAMA_BASE_URL=http://ollama:11434",
        f"OLLAMA_MODEL={ollama_model}",
        f"LLM_PROVIDER={llm_choice}",
        "",
        "# ── Notifications ────────────────────────────────────────────────────────────",
        f"TELEGRAM_BOT_TOKEN={config.get('telegram_bot_token', '')}",
        f"DISCORD_BOT_TOKEN={config.get('discord_bot_token', '')}",
        f"DISCORD_GUILD_ID={config.get('discord_guild_id', '')}",
        "",
        f"EMAIL_PROVIDER={email_provider}",
        f"SENDGRID_API_KEY={config.get('sendgrid_api_key', '')}",
        f"SMTP_HOST={config.get('smtp_host', 'localhost')}",
        f"SMTP_PORT={config.get('smtp_port', '587')}",
        f"SMTP_USER={config.get('smtp_user', '')}",
        f"SMTP_PASSWORD={config.get('smtp_password', '')}",
        f"EMAIL_FROM={config.get('email_from', 'noreply@jhans.local')}",
        "",
        "# ── Security ─────────────────────────────────────────────────────────────────",
        "ALLOWED_IPS=127.0.0.1",
        "JWT_ALGORITHM=HS256",
        "JWT_EXPIRY_HOURS=8",
        "TOTP_ISSUER=jH_ANS",
        "",
        "# ── Crawling ─────────────────────────────────────────────────────────────────",
        "CRAWL_MAX_CONCURRENCY=5",
        "CRAWL_INTERVAL_HOURS=4",
        "",
        "# ── System portal accounts ───────────────────────────────────────────────────",
        f"NAUKRI_SYSTEM_EMAIL={config.get('naukri_system_email', '')}",
        f"NAUKRI_SYSTEM_PASSWORD={config.get('naukri_system_password', '')}",
        f"LINKEDIN_SYSTEM_EMAIL={config.get('linkedin_system_email', '')}",
        f"LINKEDIN_SYSTEM_PASSWORD={config.get('linkedin_system_password', '')}",
        f"GLASSDOOR_SYSTEM_EMAIL={config.get('glassdoor_system_email', '')}",
        f"GLASSDOOR_SYSTEM_PASSWORD={config.get('glassdoor_system_password', '')}",
        f"INDEED_SYSTEM_EMAIL={config.get('indeed_system_email', '')}",
        f"INDEED_SYSTEM_PASSWORD={config.get('indeed_system_password', '')}",
        f"MONSTER_SYSTEM_EMAIL={config.get('monster_system_email', '')}",
        f"MONSTER_SYSTEM_PASSWORD={config.get('monster_system_password', '')}",
        f"SHINE_SYSTEM_EMAIL={config.get('shine_system_email', '')}",
        f"SHINE_SYSTEM_PASSWORD={config.get('shine_system_password', '')}",
        "",
        "# ── First Admin (used only at initial bootstrap) ─────────────────────────────",
        f"BOOTSTRAP_ADMIN_NAME={config.get('admin_name', '')}",
        f"BOOTSTRAP_ADMIN_EMAIL={config.get('admin_email', '')}",
        f"BOOTSTRAP_ADMIN_PASSWORD={config.get('admin_password', '')}",
    ]

    env_content = "\n".join(lines) + "\n"
    env_path = os.path.join(install_dir, ".env")

    with open(env_path, "w", encoding="utf-8") as f:
        f.write(env_content)

    # Restrict permissions on non-Windows
    try:
        import stat
        os.chmod(env_path, stat.S_IRUSR | stat.S_IWUSR)
    except Exception:
        pass

    return env_path
